name: node-auth-svc

on:
  push:
    branches:
      - main
      - feature/initial-commit
    paths:
      - .github/workflows/node-auth-svc.yml

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
      TEST_MONGO_URL: ${{ secrets.TEST_MONGO_URL }}
    services:
      redis-server:
        image: redis
        ports:
          - 6379/tcp
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1-npm-deps-

      - name: Setup redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 4
          redis-container-name: redis-server

      - run: npm ci

      - run: npm run test
