name: node-auth-svc

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/node-auth-svc.yml

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
      TEST_MONGO_URL: ${{ secrets.TEST_MONGO_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1-npm-deps-

      - name: Setup redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: 6
          redis-container-name: redis-server

      - name: Install redis cli
        run: sudo apt-get install -y redis-tools

      - name: Verify that redis is up
        run: redis-cli ping

      - run: npm ci

      - run: npm run test
